PORT: 3000

# Gulp will reference these paths when it copies files
PATHS:
  server: "."
  # Path to dist folder
  dist: "dist"
  root: "."
  # Path to demo folder
  demo: 
    dist: "demo/"
    js: "src/demo/js/**/*.js"
    css: "src/demo/scss/**/*.scss"
    json: "src/demo/json/**/*.*"
    # Path to panini
    panini: "src/demo/panini/"
    pages: "src/demo/panini/pages/**/*.html"
  # Path to images folder
  images: "img/**/*.*"
  # JS
  js: 
    - "js/**/*.js"
    - "!js/umd.js"
    - "!js/index.js"
    - "!js/polyfills/**/*.js"
  index:
    - "js/index.js"
  # Path to scss folders
  css:
    - "scss/**/*.scss"
    - "!scss/inc/**/*.scss"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/awesome-sass-easing"
    - "node_modules/flexboxgrid/dist"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "js/umd.js"
