PORT: 3000

# Gulp will reference these paths when it copies files
PATHS:
  server: "../"
  # Path to dist folder
  dist: "../dist/"
  # Path to demo folder
  demo: 
    dist: "../demo/"
    js: "demo/js/**/*.js"
    css: "demo/scss/**/*.scss"
    json: "demo/json/**/*.*"
    # Path to panini
    panini: "demo/panini/"
    pages: "demo/panini/pages/**/*.html"
  # Path to images folder
  images: "img/**/*.*"
  js: 
    - "js/**/*.js"
  #  - "!js/index.js"
    - "!js/polyfills/**/*.js"
  # Path to scss folders
  css:
    - "scss/**/*.scss"
    - "!scss/inc/**/*.scss"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/awesome-sass-easing"
    - "node_modules/flexboxgrid/dist"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "js/index.js"
